'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

type Lead = { id: string; contactName: string; companyName?: string | null; email: string };
type User = { id: string; name: string | null; email: string; role: string };
type Task = { id: string; title: string; description?: string | null; dueDate?: string | null; completed: boolean; priority: string; createdAt: string; lead?: Lead | null; assignedToId?: string | null; assignedTo?: User | null };
const todayKey = () => new Date().toISOString().slice(0, 10);
const dateKey = (d?: string | null) => d ? new Date(d).toISOString().slice(0, 10) : '';
const label = (p: string) => p.charAt(0).toUpperCase() + p.slice(1);

export default function TasksPage() {
  const [tasks, setTasks] = useState<Task[]>([]); const [users, setUsers] = useState<User[]>([]); const [leads, setLeads] = useState<Lead[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [search, setSearch] = useState(''); const [view, setView] = useState<'all'|'today'|'upcoming'|'overdue'|'completed'>('all');
  const [priority, setPriority] = useState(''); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ title: '', description: '', leadId: '', dueDate: '', priority: 'medium', assignedToId: '' });
  const load = async () => { setLoading(true); setError(''); try { const [t, l, u] = await Promise.all([fetch('/api/tasks'), fetch('/api/leads'), fetch('/api/users')]); if (!t.ok) throw new Error(); const data = await t.json(); setTasks(data); if (l.ok) setLeads(await l.json()); if (u.ok) setUsers(await u.json()); } catch { setError('Could not load tasks. Please try again.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => tasks.filter(t => {
    const q = search.toLowerCase(); const matchesSearch = !q || [t.title,t.description,t.lead?.contactName,t.lead?.companyName].some(v => v?.toLowerCase().includes(q));
    const due = dateKey(t.dueDate); const today = todayKey(); let matchesView = true;
    if (view === 'today') matchesView = !t.completed && due === today; if (view === 'upcoming') matchesView = !t.completed && !!due && due > today; if (view === 'overdue') matchesView = !t.completed && !!due && due < today; if (view === 'completed') matchesView = t.completed;
    return matchesSearch && matchesView && (!priority || t.priority === priority);
  }), [tasks, search, view, priority]);
  const counts = { all: tasks.filter(t=>!t.completed).length, today: tasks.filter(t=>!t.completed && dateKey(t.dueDate)===todayKey()).length, upcoming: tasks.filter(t=>!t.completed && dateKey(t.dueDate)>todayKey()).length, overdue: tasks.filter(t=>!t.completed && dateKey(t.dueDate)<todayKey()).length, completed: tasks.filter(t=>t.completed).length };
  const createTask = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); setError(''); try { const r = await fetch('/api/tasks', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(form) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setTasks(s=>[data,...s]); setForm({title:'',description:'',leadId:'',dueDate:'',priority:'medium',assignedToId:''}); setShowForm(false); } catch (e:any) { setError(e.message || 'Failed to create task.'); } finally { setSaving(false); } };
  const update = async (id:string, data:any) => { const old=tasks; setTasks(ts=>ts.map(t=>t.id===id?{...t,...data}:t)); const r=await fetch(`/api/tasks/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); if(!r.ok){setTasks(old); setError('Could not update task.');} else {const updated=await r.json(); setTasks(ts=>ts.map(t=>t.id===id?updated:t));} };
  const remove = async (id:string) => { if(!confirm('Delete this task?')) return; const old=tasks; setTasks(ts=>ts.filter(t=>t.id!==id)); const r=await fetch(`/api/tasks/${id}`,{method:'DELETE'}); if(!r.ok){setTasks(old); setError('Could not delete task.');} };
  return <div className="min-h-screen bg-gray-50"><div className="container-custom py-10">
    <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-bold text-gray-900">Tasks & Follow-ups</h1><p className="mt-1 text-gray-600">Organize the work that keeps your prospects moving forward.</p></div><button onClick={()=>setShowForm(v=>!v)} className="rounded-lg bg-accent-600 px-5 py-3 font-medium text-white shadow-sm hover:bg-accent-700">+ New Task</button></div>
    {error && <div className="mb-5 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Open tasks',counts.all],['Due today',counts.today],['Upcoming',counts.upcoming],['Overdue',counts.overdue],['Completed',counts.completed]].map(([n,v])=><div key={String(n)} className="rounded-xl bg-white p-5 shadow-soft"><p className="text-sm text-gray-500">{n}</p><p className="mt-2 text-3xl font-bold text-gray-900">{v}</p></div>)}</div>
    {showForm && <form onSubmit={createTask} className="mb-6 rounded-xl bg-white p-6 shadow-soft"><h2 className="mb-5 text-lg font-semibold">Create a task</h2><div className="grid gap-4 md:grid-cols-2"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Task title e.g. Follow up with client" className="rounded-lg border border-gray-300 px-4 py-3"/><select value={form.leadId} onChange={e=>setForm({...form,leadId:e.target.value})} className="rounded-lg border border-gray-300 px-4 py-3"><option value="">No lead attached</option>{leads.map(l=><option key={l.id} value={l.id}>{l.contactName}{l.companyName?` — ${l.companyName}`:''}</option>)}</select><select value={form.assignedToId} onChange={e=>setForm({...form,assignedToId:e.target.value})} className="rounded-lg border border-gray-300 px-4 py-3"><option value="">Unassigned</option>{users.map(u=><option key={u.id} value={u.id}>{u.name || u.email} · {u.role}</option>)}</select><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Notes or instructions (optional)" className="min-h-24 rounded-lg border border-gray-300 px-4 py-3 md:col-span-2"/><input type="datetime-local" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} className="rounded-lg border border-gray-300 px-4 py-3"/><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="rounded-lg border border-gray-300 px-4 py-3"><option value="low">Low priority</option><option value="medium">Medium priority</option><option value="high">High priority</option></select></div><div className="mt-5 flex gap-3"><button disabled={saving} className="rounded-lg bg-accent-600 px-5 py-3 font-medium text-white disabled:opacity-60">{saving?'Saving...':'Create Task'}</button><button type="button" onClick={()=>setShowForm(false)} className="rounded-lg border border-gray-300 px-5 py-3">Cancel</button></div></form>}
    <div className="rounded-xl bg-white shadow-soft"><div className="flex flex-col gap-3 border-b border-gray-100 p-5 lg:flex-row"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks or leads..." className="flex-1 rounded-lg border border-gray-300 px-4 py-2.5"/><select value={priority} onChange={e=>setPriority(e.target.value)} className="rounded-lg border border-gray-300 px-4 py-2.5"><option value="">All priorities</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div><div className="flex gap-2 overflow-x-auto border-b border-gray-100 px-5 py-3">{(['all','today','upcoming','overdue','completed'] as const).map(v=><button key={v} onClick={()=>setView(v)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-medium ${view===v?'bg-accent-100 text-accent-800':'text-gray-600 hover:bg-gray-50'}`}>{v==='all'?'All':label(v)} ({counts[v]})</button>)}</div>
    {loading?<div className="p-10 text-center text-gray-500">Loading tasks...</div>:filtered.length===0?<div className="p-12 text-center"><div className="text-4xl">✓</div><h3 className="mt-3 font-semibold text-gray-900">No tasks here</h3><p className="mt-1 text-sm text-gray-500">Create a task to start tracking your follow-ups and daily work.</p></div>:<div className="divide-y divide-gray-100">{filtered.map(t=>{const overdue=!t.completed && !!t.dueDate && dateKey(t.dueDate)<todayKey(); return <div key={t.id} className="flex flex-col gap-4 p-5 md:flex-row md:items-center"><input type="checkbox" checked={t.completed} onChange={e=>update(t.id,{completed:e.target.checked})} className="h-5 w-5 accent-current"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={`font-semibold ${t.completed?'text-gray-400 line-through':'text-gray-900'}`}>{t.title}</p><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${t.priority==='high'?'bg-red-50 text-red-700':t.priority==='medium'?'bg-amber-50 text-amber-700':'bg-green-50 text-green-700'}`}>{label(t.priority)}</span></div>{t.description&&<p className="mt-1 text-sm text-gray-500">{t.description}</p>}<div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-gray-500">{t.lead&&<Link href={`/leads/${t.lead.id}`} className="font-medium text-accent-700 hover:underline">👤 {t.lead.contactName}{t.lead.companyName?` · ${t.lead.companyName}`:''}</Link>}{t.assignedTo&&<span>👤 {t.assignedTo.name || t.assignedTo.email}</span>}{t.dueDate&&<span className={overdue?'font-semibold text-red-600':''}>📅 {new Date(t.dueDate).toLocaleString()}{overdue?' · Overdue':''}</span>}</div></div><div className="flex items-center gap-2"><select value={t.priority} onChange={e=>update(t.id,{priority:e.target.value})} className="rounded-lg border border-gray-200 px-3 py-2 text-sm"><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><button onClick={()=>remove(t.id)} className="rounded-lg px-3 py-2 text-sm text-red-600 hover:bg-red-50">Delete</button></div></div>})}</div>}</div>
  </div></div>;
}
