'use client';
import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';

type Ticket = { id:string; subject:string; description:string; status:string; priority:string; category:string; createdAt:string; updatedAt:string; _count:{messages:number} };
type Detail = Ticket & { requester:{name:string|null;email:string}; messages:Array<{id:string;body:string;authorEmail:string;isInternal:boolean;createdAt:string;authorUser?:{name:string|null;email:string}|null}> };
const statuses=['OPEN','IN_PROGRESS','WAITING_ON_CUSTOMER','RESOLVED','CLOSED']; const categories=['GENERAL','BILLING','BUG','ACCOUNT','FEATURE','SECURITY']; const priorities=['LOW','NORMAL','HIGH','URGENT'];
const pretty=(s:string)=>s.split('_').join(' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
export default function SupportPage(){
 const [tickets,setTickets]=useState<Ticket[]>([]),[selected,setSelected]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const [form,setForm]=useState({subject:'',description:'',category:'GENERAL',priority:'NORMAL'}),[reply,setReply]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/support/tickets',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error);setTickets(j);if(selected){const d=await fetch('/api/support/tickets/'+selected.id,{cache:'no-store'});if(d.ok)setSelected(await d.json())}}catch(e:any){setError(e.message||'Could not load support')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const open=async(id:string)=>{const r=await fetch('/api/support/tickets/'+id);const j=await r.json();if(r.ok)setSelected(j);else setError(j.error||'Could not open ticket')};
 const create=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/support/tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw Error(j.error);setForm({subject:'',description:'',category:'GENERAL',priority:'NORMAL'});setSuccess('Support ticket created.');await open(j.id);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const sendReply=async(e:FormEvent)=>{e.preventDefault();if(!selected||!reply.trim())return;setBusy(true);try{const r=await fetch('/api/support/tickets/'+selected.id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:reply})});const j=await r.json();if(!r.ok)throw Error(j.error);setReply('');await open(selected.id);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const changeStatus=async(status:string)=>{if(!selected)return;const r=await fetch('/api/support/tickets/'+selected.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const j=await r.json();if(!r.ok)setError(j.error);else await open(selected.id);load()};
 return <div className="mx-auto max-w-7xl space-y-6"><div><p className="text-sm font-bold text-sky-600">CUSTOMER CARE</p><h1 className="text-3xl font-black text-gray-900 dark:text-white">Support Center</h1><p className="mt-1 text-sm text-gray-500">Contact Versaly support, follow replies, and keep your workspace moving.</p></div>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{success&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{success}</div>}
 <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-gray-900"><h2 className="font-bold">Open a support ticket</h2><form onSubmit={create} className="mt-4 space-y-3"><input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="What do you need help with?" className="w-full rounded-xl border p-3 text-sm"/><div className="grid grid-cols-2 gap-2"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="rounded-xl border p-3 text-sm">{categories.map(x=><option key={x}>{x}</option>)}</select><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})} className="rounded-xl border p-3 text-sm">{priorities.map(x=><option key={x}>{x}</option>)}</select></div><textarea required minLength={10} rows={7} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe the issue, what you expected, and what happened..." className="w-full rounded-xl border p-3 text-sm"/><button disabled={busy} className="w-full rounded-xl bg-sky-600 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?'Sending...':'Create ticket'}</button></form><div className="mt-7 border-t pt-5"><h3 className="text-sm font-bold">Your tickets</h3>{loading?<p className="mt-3 text-sm text-gray-500">Loading...</p>:tickets.length===0?<p className="mt-3 text-sm text-gray-500">No tickets yet.</p>:<div className="mt-3 space-y-2">{tickets.map(t=><button key={t.id} onClick={()=>open(t.id)} className={`w-full rounded-xl border p-3 text-left hover:bg-gray-50 ${selected?.id===t.id?'border-sky-400 bg-sky-50/50':''}`}><div className="flex items-start justify-between gap-2"><span className="text-sm font-semibold">{t.subject}</span><span className="rounded-full border px-2 py-0.5 text-[10px]">{pretty(t.status)}</span></div><p className="mt-1 text-xs text-gray-500">{pretty(t.category)} · {t._count.messages} messages</p></button>)}</div>}</div></section>
 <section className="rounded-2xl border bg-white shadow-sm dark:bg-gray-900">{!selected?<div className="flex min-h-[520px] items-center justify-center p-8 text-center text-gray-500"><div><div className="text-4xl">💬</div><p className="mt-3 font-semibold">Select a ticket to view the conversation</p><p className="mt-1 text-sm">Our support team can help with billing, bugs, accounts, and product questions.</p></div></div>:<><div className="border-b p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-xl font-black">{selected.subject}</h2><p className="mt-1 text-xs text-gray-500">{pretty(selected.category)} · {pretty(selected.priority)} · opened {new Date(selected.createdAt).toLocaleString()}</p></div><select value={selected.status} onChange={e=>changeStatus(e.target.value)} className="rounded-lg border px-3 py-2 text-xs">{statuses.map(x=><option key={x}>{x}</option>)}</select></div></div><div className="max-h-[430px] space-y-4 overflow-y-auto p-5">{selected.messages.filter(m=>!m.isInternal).map(m=><div key={m.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><span className="text-xs font-bold">{m.authorUser?.name||m.authorEmail}</span><span className="text-[10px] text-gray-400">{new Date(m.createdAt).toLocaleString()}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-gray-700 dark:text-gray-200">{m.body}</p></div>)}</div><form onSubmit={sendReply} className="border-t p-5"><textarea rows={4} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a reply..." className="w-full rounded-xl border p-3 text-sm"/><button disabled={busy||!reply.trim()||selected.status==='CLOSED'} className="mt-2 rounded-xl bg-gray-900 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">Send reply</button></form></>}</section></div></div>;
}
