'use client';

import Link from 'next/link';
import { useState } from 'react';

const plans = [
  { name: 'Starter', price: 29, annual: 24, description: 'A focused workspace for independent operators.', features: ['1,000 active leads', '3 team seats', 'Visual deal pipeline', 'Email sequences & tasks', 'Core conversion metrics'] },
  { name: 'Growth Pro', price: 79, annual: 64, description: 'The operating system for ambitious sales teams.', popular: true, features: ['5,000 active leads', '10 team seats', 'Email & WhatsApp sequences', 'Role-based permissions', 'Revenue trajectory analytics', 'Priority support'] },
  { name: 'Enterprise Scale', price: 199, annual: 159, description: 'Control, automation and scale for larger teams.', features: ['100,000 active leads', '50 team seats', 'Advanced workflows & webhooks', 'Custom reports and exports', 'Multi-currency billing', 'Dedicated account manager'] },
];

const faqs = [
  ['How does the free trial work?', 'Start with the complete Growth Pro experience for 14 days. No credit card is required, and you can invite your team and import leads immediately.'],
  ['Can I change plans later?', 'Yes. Upgrade or downgrade from Subscription & Billing whenever your team changes.'],
  ['Is each company’s data isolated?', 'Yes. Every organization has its own workspace, users, leads, tasks and pipelines.'],
  ['Which currencies are supported?', 'Straten supports USD, KES, EUR and GBP formatting, with billing options depending on your plan.'],
];

function Arrow() { return <span aria-hidden>↗</span>; }

export default function LandingPage() {
  const [annual, setAnnual] = useState(false);
  const [faq, setFaq] = useState<number | null>(0);

  return (
    <main className="min-h-screen overflow-hidden bg-[#061826] text-white">
      <header className="sticky top-0 z-50 border-b border-white/10 bg-[#061826]/85 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
          <Link href="/" className="flex items-center gap-3">
            <span className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-sky-400 to-sky-700 text-lg font-black text-white shadow-lg shadow-sky-600/20">S</span>
            <span><b className="block text-lg tracking-tight">Straten<span className="text-sky-500">CRM</span></b><small className="block text-[9px] font-bold uppercase tracking-[.22em] text-gray-400">Sales, with direction</small></span>
          </Link>
          <nav className="hidden items-center gap-8 text-sm font-semibold text-gray-300 md:flex"><a href="#features">Platform</a><a href="#workflow">Workflow</a><a href="#pricing">Pricing</a><a href="#faqs">FAQs</a></nav>
          <div className="flex items-center gap-3"><Link href="/auth/signin" className="hidden px-3 py-2 text-sm font-bold text-gray-300 hover:text-white sm:block">Sign in</Link><Link href="/auth/signup?plan=GROWTH_PRO" className="rounded-lg bg-sky-600 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-sky-600/20">Start free trial <Arrow /></Link></div>
        </div>
      </header>

      <section className="relative px-5 pb-20 pt-16 lg:px-8 lg:pb-28 lg:pt-24">
        <div className="pointer-events-none absolute -left-40 top-0 h-[520px] w-[520px] rounded-full bg-sky-400/15 blur-3xl" /><div className="pointer-events-none absolute -right-40 top-20 h-[420px] w-[420px] rounded-full bg-indigo-400/10 blur-3xl" />
        <div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.9fr_1.1fr]">
          <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-sky-200 bg-sky-50 px-3 py-1.5 text-xs font-bold text-sky-700 dark:border-sky-800 dark:bg-sky-950/40 dark:text-sky-300"><span className="h-2 w-2 rounded-full bg-sky-500" /> Built for teams that refuse to lose momentum</div><h1 className="max-w-2xl text-5xl font-black leading-[1.02] tracking-[-.055em] sm:text-7xl">Your pipeline.<br /><span className="text-sky-500">A clearer next move.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-gray-600 dark:text-gray-300">Straten brings leads, conversations, tasks and revenue into one calm command center—so your team always knows what to do next.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/auth/signup?plan=GROWTH_PRO" className="rounded-xl bg-sky-600 px-6 py-4 text-center text-sm font-bold text-white shadow-xl shadow-sky-600/20">Start your 14-day trial <Arrow /></Link><a href="#workflow" className="rounded-xl border border-gray-200 px-6 py-4 text-center text-sm font-bold dark:border-white/15">See how it works ↓</a></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-xs font-semibold text-gray-500 dark:text-gray-400"><span>✓ No card required</span><span>✓ Cancel anytime</span><span>✓ KES-ready billing</span></div></div>
          <div className="relative"><div className="absolute -inset-5 rounded-[2rem] bg-sky-500/10 blur-2xl" /><div className="relative rounded-[1.7rem] border border-gray-200 bg-gray-50 p-3 shadow-2xl dark:border-white/10 dark:bg-[#0a2233]"><div className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-white/10 dark:bg-[#081b2a]"><div className="flex items-center justify-between border-b border-gray-100 pb-4 dark:border-white/10"><div><p className="text-xs font-bold text-gray-400">MONDAY · 09:41</p><h3 className="mt-1 text-lg font-black">Good morning, team.</h3></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-[10px] font-bold text-emerald-700">Live workspace</span></div><div className="mt-5 grid grid-cols-3 gap-3">{[['Active leads','1,284','+18.4%'],['Pipeline value','KES 4.8M','+12.7%'],['Win rate','34.8%','+4.2%']].map(([a,b,c]) => <div key={a} className="rounded-xl border border-gray-100 p-3 dark:border-white/10"><p className="text-[10px] font-semibold text-gray-400">{a}</p><p className="mt-2 text-lg font-black">{b}</p><p className="mt-1 text-[10px] font-bold text-emerald-600">{c}</p></div>)}</div><div className="mt-5 rounded-xl border border-gray-100 p-4 dark:border-white/10"><div className="flex items-center justify-between"><p className="text-xs font-bold">Revenue trajectory</p><span className="text-[10px] text-gray-400">Last 6 months</span></div><div className="mt-5 flex h-32 items-end gap-2">{[35,48,42,68,62,92,78,100,86,110,98,124].map((h,i)=><div key={i} className="flex-1 rounded-t-md bg-sky-500/20" style={{height:`${h}px`}}><div className="h-full rounded-t-md bg-sky-500" style={{height:`${Math.min(100,h*0.72)}%`}} /></div>)}</div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-sky-50 p-3 dark:bg-sky-950/30"><p className="text-[10px] font-bold text-sky-700 dark:text-sky-300">Next best action</p><p className="mt-1 text-xs font-bold">Follow up with 8 warm leads</p></div><div className="rounded-xl bg-gray-100 p-3 dark:bg-white/5"><p className="text-[10px] font-bold text-gray-500">Team pulse</p><p className="mt-1 text-xs font-bold">12 tasks due today</p></div></div></div></div></div>
        </div>
      </section>

      <section id="features" className="border-y border-gray-200/70 bg-gray-50/70 px-5 py-16 dark:border-white/10 dark:bg-white/[.02] lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.25em] text-sky-500">One system. Less chasing.</p><h2 className="mt-4 max-w-2xl text-4xl font-black tracking-tight sm:text-5xl">Everything your sales team needs to move with intent.</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{[['01','Capture once','Bring every prospect into a structured workspace with clean ownership and context.'],['02','Work the signal','Prioritize follow-ups, automate routine outreach and keep every conversation attached.'],['03','Close the loop','See what converts, where revenue is stuck and which actions create momentum.']].map(([n,t,d])=><article key={n} className="rounded-2xl border border-gray-200 bg-white p-7 dark:border-white/10 dark:bg-[#0a2233]"><span className="text-sm font-black text-sky-500">{n}</span><h3 className="mt-12 text-xl font-black">{t}</h3><p className="mt-3 text-sm leading-7 text-gray-500 dark:text-gray-300">{d}</p></article>)}</div></div></section>

      <section id="workflow" className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.25em] text-sky-500">Designed around the day-to-day</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">From first contact to signed deal, without the gaps.</h2><p className="mt-5 max-w-lg text-gray-500 dark:text-gray-300">A workspace that connects the small actions to the big picture. Less tab switching. More meaningful progress.</p></div><div className="space-y-3">{[['Capture','Forms, imports and integrations feed one shared pipeline.'],['Coordinate','Assign owners, schedule tasks and keep every teammate aligned.'],['Convert','Use stage insights and outreach history to make sharper decisions.']].map(([t,d],i)=><div key={t} className="flex gap-4 rounded-2xl border border-gray-200 p-5 dark:border-white/10"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-sky-500 text-sm font-black text-white">{i+1}</span><div><h3 className="font-black">{t}</h3><p className="mt-1 text-sm text-gray-500 dark:text-gray-300">{d}</p></div></div>)}</div></div></section>

      <section id="pricing" className="bg-gray-50 px-5 py-20 dark:bg-white/[.025] lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.25em] text-sky-500">Simple monthly plans</p><h2 className="mt-3 text-4xl font-black tracking-tight">Start small. Scale confidently.</h2></div><div className="flex items-center gap-3 rounded-full border border-gray-200 bg-white p-1 text-xs font-bold dark:border-white/10 dark:bg-[#0a2233]"><button onClick={()=>setAnnual(false)} className={`rounded-full px-4 py-2 ${!annual?'bg-sky-600 text-white':''}`}>Monthly</button><button onClick={()=>setAnnual(true)} className={`rounded-full px-4 py-2 ${annual?'bg-sky-600 text-white':''}`}>Annual · save 20%</button></div></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{plans.map((p)=><div key={p.name} className={`relative rounded-2xl border p-7 ${p.popular?'border-sky-500 bg-[#08263a] text-white shadow-xl shadow-sky-900/10':'border-gray-200 bg-white dark:border-white/10 dark:bg-[#0a2233]'}`}>{p.popular&&<span className="absolute right-5 top-5 rounded-full bg-sky-500 px-3 py-1 text-[10px] font-black uppercase">Most popular</span>}<h3 className="text-xl font-black">{p.name}</h3><p className={`mt-3 min-h-12 text-sm ${p.popular?'text-gray-300':'text-gray-500 dark:text-gray-300'}`}>{p.description}</p><div className="mt-7"><span className="text-5xl font-black">${annual?p.annual:p.price}</span><span className="text-sm text-gray-400"> / month</span></div><Link href={`/auth/signup?plan=${p.name.toUpperCase().replace(' ','_')}`} className={`mt-7 block rounded-xl px-4 py-3 text-center text-sm font-bold ${p.popular?'bg-sky-500 text-white':'border border-gray-200 dark:border-white/15'}`}>Choose {p.name} <Arrow /></Link><ul className="mt-7 space-y-3 text-sm">{p.features.map(f=><li key={f} className="flex gap-2"><span className="text-sky-500">✓</span>{f}</li>)}</ul></div>)}</div></div></section>

      <section id="faqs" className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-3xl"><p className="text-center text-xs font-black uppercase tracking-[.25em] text-sky-500">Questions, answered</p><h2 className="mt-3 text-center text-4xl font-black tracking-tight">A few things worth knowing.</h2><div className="mt-10 divide-y divide-gray-200 border-y border-gray-200 dark:divide-white/10 dark:border-white/10">{faqs.map(([q,a],i)=><div key={q} className="py-5"><button onClick={()=>setFaq(faq===i?null:i)} className="flex w-full items-center justify-between text-left font-bold">{q}<span className="text-xl text-sky-500">{faq===i?'−':'+'}</span></button>{faq===i&&<p className="mt-3 max-w-2xl pr-8 text-sm leading-7 text-gray-500 dark:text-gray-300">{a}</p>}</div>)}</div></div></section>
      <footer className="border-t border-gray-200 px-5 py-8 dark:border-white/10 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-xs text-gray-500 sm:flex-row"><span>© 2026 Straten CRM. Built for better sales days.</span><span>Secure workspaces · Monthly subscriptions · 14-day trial</span></div></footer>
    </main>
  );
}
