import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import prisma from '@/lib/prisma';
import { summarizeMeetingTranscript } from '@/lib/aiCopilot';

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    const organizationId = session?.user?.organizationId;
    if (!session || !organizationId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    const { rawTranscript, leadId, autoCreateTasks } = body;

    if (!rawTranscript || typeof rawTranscript !== 'string' || !rawTranscript.trim()) {
      return NextResponse.json({ error: 'Missing or empty rawTranscript' }, { status: 400 });
    }

    let leadContext: { contactName?: string; companyName?: string; dealValue?: number | null } | undefined = undefined;
    let validatedLeadId: string | null = null;

    if (leadId) {
      const lead = await prisma.lead.findFirst({
        where: { id: leadId, organizationId },
      });
      if (lead) {
        validatedLeadId = lead.id;
        leadContext = {
          contactName: lead.contactName,
          companyName: lead.companyName || undefined,
          dealValue: lead.dealValue,
        };
      }
    }

    // Run AI meeting summarization
    const result = summarizeMeetingTranscript(rawTranscript, leadContext);

    let summaryRecord = null;
    let tasksCreatedCount = 0;

    // Save summary if associated with a lead
    if (validatedLeadId) {
      summaryRecord = await prisma.aiMeetingSummary.create({
        data: {
          organizationId,
          leadId: validatedLeadId,
          title: result.title,
          rawTranscript,
          summary: result.summary,
          actionItems: JSON.stringify(result.actionItems),
          objections: JSON.stringify(result.objections),
          keyDecisions: JSON.stringify(result.keyDecisions),
          sentiment: result.sentiment,
        },
      });

      // Auto-create CRM tasks if requested
      if (autoCreateTasks && result.actionItems.length > 0) {
        for (const item of result.actionItems) {
          try {
            await prisma.task.create({
              data: {
                organizationId,
                leadId: validatedLeadId,
                title: item.title,
                description: `Auto-generated by AI Copilot from meeting transcript: "${result.title}"`,
                priority: item.priority || 'medium',
                dueDate: item.dueDate ? new Date(item.dueDate) : new Date(Date.now() + 3 * 86400000),
              },
            });
            tasksCreatedCount += 1;
          } catch (e) {
            console.error('Failed to create task from action item:', e);
          }
        }
      }

      // Record activity event
      try {
        await prisma.activityEvent.create({
          data: {
            leadId: validatedLeadId,
            type: 'AI_MEETING_SUMMARIZED',
            action: `AI Copilot processed transcript: "${result.title}" with ${result.actionItems.length} action items (${tasksCreatedCount} tasks created).`,
          },
        });
      } catch (e) {
        // Non-blocking
      }
    }

    return NextResponse.json({
      success: true,
      summary: result,
      summaryId: summaryRecord?.id || null,
      tasksCreated: tasksCreatedCount,
    });
  } catch (error: any) {
    console.error('Error in POST /api/copilot/summarize:', error);
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 500 });
  }
}
