'use client';
import { useEffect, useState } from 'react';
const field='mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:border-accent-500 focus:outline-none dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100';
const events=['lead.created','lead.updated','lead.stage_changed','task.created','task.completed','activity.created','calendar.created','workflow.executed'];
export default function IntegrationsPage(){
 const [origin,setOrigin]=useState(''); const [keys,setKeys]=useState<any[]>([]); const [hooks,setHooks]=useState<any[]>([]); const [hookEvents,setHookEvents]=useState<string[]>(events); const [name,setName]=useState(''); const [url,setUrl]=useState(''); const [selected,setSelected]=useState<string[]>(['lead.created']); const [newSecret,setNewSecret]=useState(''); const [newKey,setNewKey]=useState(''); const [message,setMessage]=useState('');
 const load=async()=>{const [a,b]=await Promise.all([fetch('/api/developer/keys'),fetch('/api/developer/webhooks')]); if(a.ok)setKeys(await a.json()); if(b.ok){const j=await b.json();setHooks(j.webhooks||[]);setHookEvents(j.events||events)}};
 useEffect(()=>{setOrigin(window.location.origin);load()},[]);
 const createKey=async()=>{setMessage('');const r=await fetch('/api/developer/keys',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:name||'Production API key'})});const j=await r.json();if(!r.ok){setMessage(j.error||'Unable to create key');return}setNewKey(j.key);setName('');load()};
 const revoke=async(id:string)=>{await fetch('/api/developer/keys?id='+encodeURIComponent(id),{method:'DELETE'});load()};
 const createHook=async()=>{const r=await fetch('/api/developer/webhooks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:name||'CRM webhook',url,events:selected})});const j=await r.json();if(!r.ok){setMessage(j.error||'Unable to create webhook');return}setNewSecret(j.secret);setUrl('');setName('');load()};
 const delHook=async(id:string)=>{await fetch('/api/developer/webhooks?id='+encodeURIComponent(id),{method:'DELETE'});load()};
 const toggle=(e:string)=>setSelected(v=>v.includes(e)?v.filter(x=>x!==e):[...v,e]);
 return <div className="mx-auto max-w-6xl space-y-6">
  <div><p className="text-sm font-medium text-accent-700">Developer platform</p><h1 className="mt-1 text-3xl font-bold text-gray-900 dark:text-gray-100">Integrations & API</h1><p className="mt-2 text-gray-600 dark:text-gray-400">Connect websites, automation platforms and your own software with workspace-scoped credentials and signed events.</p></div>
  {message&&<div className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">{message}</div>}
  {(newKey||newSecret)&&<div className="rounded-xl border border-emerald-300 bg-emerald-50 p-5 dark:border-emerald-800 dark:bg-emerald-950/30"><h2 className="font-semibold text-emerald-900 dark:text-emerald-200">Save this secret now</h2><p className="mt-1 text-sm text-emerald-800 dark:text-emerald-300">For security, the full secret will not be shown again.</p>{newKey&&<code className="mt-3 block break-all rounded bg-white p-3 text-xs dark:bg-gray-950">{newKey}</code>}{newSecret&&<code className="mt-3 block break-all rounded bg-white p-3 text-xs dark:bg-gray-950">{newSecret}</code>}<button className="mt-3 rounded-lg border px-3 py-2 text-sm" onClick={()=>{navigator.clipboard.writeText(newKey||newSecret);setMessage('Secret copied.')}}>Copy secret</button></div>}
  <div className="grid gap-6 lg:grid-cols-2">
   <section className="rounded-xl border border-gray-200 bg-white p-6 shadow-soft dark:border-gray-800 dark:bg-gray-950"><h2 className="text-xl font-semibold">API keys</h2><p className="mt-1 text-sm text-gray-500">Create credentials for the versioned API. Full keys are displayed only once.</p><div className="mt-4 flex gap-2"><input className={field+' mt-0'} placeholder="Key name" value={name} onChange={e=>setName(e.target.value)}/><button className="btn-primary whitespace-nowrap" onClick={createKey}>Create key</button></div><div className="mt-5 space-y-2">{keys.map(k=><div key={k.id} className="flex items-center justify-between rounded-lg border p-3 text-sm dark:border-gray-800"><div><div className="font-medium">{k.name}</div><div className="text-xs text-gray-500">{k.keyPrefix}… · {k.revokedAt?'Revoked':k.lastUsedAt?`Used ${new Date(k.lastUsedAt).toLocaleDateString()}`:'Never used'}</div></div>{!k.revokedAt&&<button onClick={()=>revoke(k.id)} className="text-xs font-semibold text-red-600">Revoke</button>}</div>)}{!keys.length&&<p className="text-sm text-gray-500">No API keys yet.</p>}</div></section>
   <section className="rounded-xl border border-gray-200 bg-white p-6 shadow-soft dark:border-gray-800 dark:bg-gray-950"><h2 className="text-xl font-semibold">Outbound webhooks</h2><p className="mt-1 text-sm text-gray-500">Receive signed CRM events at your server, n8n, Make, Zapier or another endpoint.</p><input className={field} placeholder="Webhook name" value={name} onChange={e=>setName(e.target.value)}/><input className={field} placeholder="https://example.com/webhooks" value={url} onChange={e=>setUrl(e.target.value)}/><div className="mt-3 grid grid-cols-2 gap-2 text-xs">{hookEvents.map(e=><label key={e} className="flex items-center gap-2"><input type="checkbox" checked={selected.includes(e)} onChange={()=>toggle(e)}/>{e}</label>)}</div><button className="btn-primary mt-4" onClick={createHook}>Add webhook</button><div className="mt-5 space-y-2">{hooks.map(h=><div key={h.id} className="flex items-center justify-between rounded-lg border p-3 text-sm dark:border-gray-800"><div><div className="font-medium">{h.name}</div><div className="max-w-[260px] truncate text-xs text-gray-500">{h.url} · {h.failureCount} failures</div></div><button onClick={()=>delHook(h.id)} className="text-xs font-semibold text-red-600">Delete</button></div>)}</div></section>
  </div>
  <section className="rounded-xl border border-blue-200 bg-blue-50 p-6 dark:border-blue-900/60 dark:bg-blue-950/30"><h2 className="text-xl font-semibold">Versioned API</h2><p className="mt-2 text-sm text-gray-600 dark:text-gray-300">Base endpoint: <code>{origin}/api/v1</code></p><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-lg bg-white/80 p-4 dark:bg-gray-950/60"><div className="font-mono text-sm">POST /leads</div><p className="mt-1 text-sm text-gray-500">Capture a lead and run normal assignment, tasks and automations.</p></div><div className="rounded-lg bg-white/80 p-4 dark:bg-gray-950/60"><div className="font-mono text-sm">GET /leads?search=</div><p className="mt-1 text-sm text-gray-500">Read up to 100 workspace leads using an API key.</p></div></div><pre className="mt-4 overflow-x-auto rounded-lg bg-gray-950 p-4 text-xs leading-6 text-gray-100">{`curl -X POST ${origin}/api/v1/leads \\\n  -H "Authorization: Bearer YOUR_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '{"contactName":"Jane Smith","email":"jane@example.com","leadSource":"WEBSITE_FORM"}'`}</pre></section>
  <section className="rounded-xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-950"><h2 className="font-semibold">Existing inbound integrations</h2><p className="mt-2 text-sm text-gray-500">The existing public website lead form, secure lead webhook, and Meta Lead Ads integration remain available. Phase 15 adds workspace-specific developer credentials and outbound event delivery on top.</p></section>
 </div>
}
