import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '../../../../../lib/auth';
import prisma from '../../../../../lib/prisma';
import crypto from 'crypto';
const EVENTS=['lead.created','lead.updated','lead.stage_changed','task.created','task.completed','activity.created','calendar.created','workflow.executed'];
async function get(){return getServerSession(authOptions)}
export async function GET(){const s=await get();if(!s?.user?.organizationId)return NextResponse.json({error:'Unauthorized'},{status:401});const rows=await prisma.webhookEndpoint.findMany({where:{organizationId:s.user.organizationId},select:{id:true,name:true,url:true,events:true,isActive:true,lastDeliveredAt:true,failureCount:true,createdAt:true},orderBy:{createdAt:'desc'}});return NextResponse.json({events:EVENTS,webhooks:rows});}
export async function POST(req:NextRequest){const s=await get();if(!s?.user?.organizationId||!['ADMIN','MANAGER'].includes(s.user.role||''))return NextResponse.json({error:'Admin or manager access required.'},{status:403});const body=await req.json();const name=String(body.name||'').trim(),url=String(body.url||'').trim();let parsed:URL;try{parsed=new URL(url);if(!/^https?:$/.test(parsed.protocol))throw new Error()}catch{return NextResponse.json({error:'A valid HTTPS/HTTP webhook URL is required.'},{status:400})}const events=Array.isArray(body.events)?body.events.filter((x:string)=>EVENTS.includes(x)||x==='*'):[];if(!name||!events.length)return NextResponse.json({error:'Name and at least one event are required.'},{status:400});const secret=`whsec_${crypto.randomBytes(24).toString('hex')}`;const row=await prisma.webhookEndpoint.create({data:{organizationId:s.user.organizationId,name,url,secret,events}});return NextResponse.json({id:row.id,name:row.name,url:row.url,events,secret,warning:'Store this signing secret securely. It is shown only once.'},{status:201});}
export async function PATCH(req:NextRequest){const s=await get();if(!s?.user?.organizationId||!['ADMIN','MANAGER'].includes(s.user.role||''))return NextResponse.json({error:'Admin or manager access required.'},{status:403});const b=await req.json();if(!b.id)return NextResponse.json({error:'Webhook id is required.'},{status:400});const data:any={};if(typeof b.isActive==='boolean')data.isActive=b.isActive;if(Array.isArray(b.events))data.events=b.events;if(b.name)data.name=String(b.name).trim();await prisma.webhookEndpoint.updateMany({where:{id:b.id,organizationId:s.user.organizationId},data});return NextResponse.json({success:true});}
export async function DELETE(req:NextRequest){const s=await get();if(!s?.user?.organizationId||!['ADMIN','MANAGER'].includes(s.user.role||''))return NextResponse.json({error:'Admin or manager access required.'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Webhook id is required.'},{status:400});await prisma.webhookEndpoint.deleteMany({where:{id,organizationId:s.user.organizationId}});return NextResponse.json({success:true});}
