import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '../../../../lib/auth';
import prisma from '../../../../lib/prisma';
import { WORKFLOW_ACTIONS, WORKFLOW_TRIGGERS } from '../../../../lib/workflows';
import { assertSubscriptionWriteAccess } from '../../../../lib/subscription';
async function ctx(){const s=await getServerSession(authOptions);return s?.user?.organizationId?{s,orgId:s.user.organizationId}:null;}
export async function GET(){const c=await ctx();if(!c)return NextResponse.json({error:'Unauthorized'},{status:401});const [workflows,executions,org]=await Promise.all([prisma.automationWorkflow.findMany({where:{organizationId:c.orgId},orderBy:{updatedAt:'desc'},include:{_count:{select:{executions:true}}}}),prisma.automationExecution.findMany({where:{organizationId:c.orgId},orderBy:{executedAt:'desc'},take:50,include:{workflow:{select:{name:true}}}}),prisma.organization.findUnique({where:{id:c.orgId},select:{automationRunLimit:true,plan:true}})]);const ids=[...new Set(executions.map(x=>x.leadId).filter(Boolean))] as string[];const leads=ids.length?await prisma.lead.findMany({where:{organizationId:c.orgId,id:{in:ids}},select:{id:true,contactName:true,companyName:true}}):[];const map=new Map(leads.map(x=>[x.id,x]));return NextResponse.json({workflows,executions:executions.map(x=>({...x,lead:x.leadId?map.get(x.leadId)||null:null})),limits:{monthlyRuns:org?.automationRunLimit||0,plan:org?.plan||'GROWTH_PRO'}});}
export async function POST(req:NextRequest){const c=await ctx();if(!c)return NextResponse.json({error:'Unauthorized'},{status:401});try{const access=await assertSubscriptionWriteAccess(c.orgId); if(access && !access.allowed) return NextResponse.json({error:access.reason||'Workspace is read-only.'},{status:403});const b=await req.json();const name=String(b.name||'').trim(),triggerType=String(b.triggerType||'').toUpperCase(),actionType=String(b.actionType||'').toUpperCase();if(!name||!(WORKFLOW_TRIGGERS as readonly string[]).includes(triggerType)||!(WORKFLOW_ACTIONS as readonly string[]).includes(actionType))return NextResponse.json({error:'Name, valid trigger, and valid action are required.'},{status:400});const w=await prisma.automationWorkflow.create({data:{organizationId:c.orgId,name,description:String(b.description||'').trim()||null,triggerType,triggerConfig:b.triggerConfig&&typeof b.triggerConfig==='object'?b.triggerConfig:{},actionType,actionConfig:b.actionConfig&&typeof b.actionConfig==='object'?b.actionConfig:{},isActive:b.isActive!==false}});return NextResponse.json(w,{status:201});}catch(e:any){if(e?.code==='P2002')return NextResponse.json({error:'A workflow with this name already exists.'},{status:409});return NextResponse.json({error:e?.message||'Could not create workflow.'},{status:500});}}
