'use client';

import { useEffect, useMemo, useState } from 'react';

type Lead = { id: string; contactName: string; companyName?: string | null; phone?: string | null };
type Config = { configured: boolean; phoneNumberIdConfigured: boolean; accessTokenConfigured: boolean; apiVersion: string };
const input = 'w-full rounded-lg border border-gray-200 px-3 py-2 text-sm outline-none focus:border-accent-400 focus:ring-2 focus:ring-accent-100';

export default function WhatsAppPage() {
  const [leads,setLeads]=useState<Lead[]>([]); const [config,setConfig]=useState<Config>({configured:false,phoneNumberIdConfigured:false,accessTokenConfigured:false,apiVersion:'v21.0'}); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');
  const [form,setForm]=useState({leadId:'',phone:'',message:''});
  const selectedLead=useMemo(()=>leads.find(l=>l.id===form.leadId)||null,[leads,form.leadId]);
  async function load(){setLoading(true);setError('');try{const [l,c]=await Promise.all([fetch('/api/leads',{cache:'no-store'}),fetch('/api/whatsapp/config',{cache:'no-store'})]);const ld=await l.json();const cd=await c.json();if(!l.ok||!c.ok)throw new Error(cd.error||'Could not load WhatsApp workspace.');const nextLeads=Array.isArray(ld)?ld:[];setLeads(nextLeads);setConfig(cd);
      if(typeof window!=='undefined'){const requestedLeadId=new URLSearchParams(window.location.search).get('leadId')||'';const requestedLead=nextLeads.find((lead:Lead)=>lead.id===requestedLeadId);if(requestedLead)setForm(v=>({...v,leadId:requestedLead.id,phone:requestedLead.phone||''}));}}catch(e:any){setError(e.message||'Could not load WhatsApp workspace.');}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  async function send(e:React.FormEvent){e.preventDefault();setError('');setSuccess('');if(!form.leadId){setError('Please select a lead.');return;}setSending(true);try{const r=await fetch('/api/whatsapp/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not send WhatsApp message.');setSuccess('WhatsApp message sent and logged in the lead outreach history.');setForm(v=>({...v,message:''}));}catch(e:any){setError(e.message||'Could not send WhatsApp message.');}finally{setSending(false);}}
  return <div className="min-h-screen bg-gray-50"><div className="container-custom py-8 !max-w-none"><div className="mb-7"><h1 className="text-2xl font-bold text-gray-800">WhatsApp Workspace</h1><p className="mt-1 text-sm text-gray-500">Send WhatsApp messages from the CRM and keep each interaction in the lead outreach history.</p></div>
  {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{success&&<div className="mb-5 rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-700">{success}</div>}
  {!config.configured&&<div className="mb-6 rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-900">WhatsApp Cloud API needs configuration</h2><p className="mt-1 text-sm text-amber-800">Add WHATSAPP_PHONE_NUMBER_ID and WHATSAPP_ACCESS_TOKEN to your environment, then restart the server. The CRM is ready to send through Meta's WhatsApp Cloud API once those credentials are connected.</p></div>}
  {loading?<div className="rounded-xl bg-white p-10 text-center text-sm text-gray-500 shadow-soft">Loading WhatsApp workspace...</div>:<div className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,0.8fr)]"><section className="rounded-xl bg-white p-6 shadow-soft"><h2 className="text-lg font-semibold text-gray-900">Compose WhatsApp Message</h2><form onSubmit={send} className="mt-6 space-y-4"><div><label className="mb-1 block text-sm font-medium text-gray-700">Lead</label><select required className={input} value={form.leadId} onChange={e=>{const lead=leads.find(l=>l.id===e.target.value);setForm({...form,leadId:e.target.value,phone:lead?.phone||''});}}><option value="">Select a lead...</option>{leads.map(l=><option key={l.id} value={l.id}>{l.contactName}{l.companyName?` — ${l.companyName}`:''}</option>)}</select></div><div><label className="mb-1 block text-sm font-medium text-gray-700">Phone number</label><input required className={input} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="2547XXXXXXXX" /><p className="mt-1 text-xs text-gray-400">Use international format. Kenyan mobile numbers can use 2547XXXXXXXX.</p></div><div><label className="mb-1 block text-sm font-medium text-gray-700">Message</label><textarea required rows={10} className={input} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Write your WhatsApp message..." /></div><button disabled={sending||!config.configured} className="btn-primary disabled:cursor-not-allowed disabled:opacity-50">{sending?'Sending...':'Send & Log WhatsApp'}</button></form></section><aside className="rounded-xl bg-white p-6 shadow-soft"><h2 className="text-lg font-semibold text-gray-900">Connection Status</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span>Cloud API</span><strong>{config.configured?'Connected':'Not configured'}</strong></div><div className="flex justify-between"><span>Phone Number ID</span><span>{config.phoneNumberIdConfigured?'Configured':'Missing'}</span></div><div className="flex justify-between"><span>Access Token</span><span>{config.accessTokenConfigured?'Configured':'Missing'}</span></div><div className="flex justify-between"><span>Graph API</span><span>{config.apiVersion}</span></div></div><div className="mt-6 rounded-lg bg-gray-50 p-4 text-sm text-gray-600">Messages sent from this workspace are logged against the selected lead and update the lead's last-contact activity.</div></aside></div>}</div></div>;
}
